export const APPLICATION_INTERFACE_ERROR =
    'EVENT/APPLICATION_INTERFACE_ERROR_ENCOUNTERED'
export const WEATHER_DATA_RECEIVED = 'EVENT/WEATHER_DATA_RECEIVED'
export const WEATHER_INFO_RECEIVED = 'EVENT/WEATHER_INFO_RECEIVED'
export const API_ERROR = 'EVENT/API_ERROR'

export const METRICS_INFO_RECEIVED = 'METRICS_INFO_RECEIVED'

export const FETCH_HALF_AN_HOURS_DATA = 'FETCH_HALF_AN_HOURS_DATA'
export const MULTIPLE_DATA_UNITS_RECEIVED = 'MULTIPLE_DATA_UNITS_RECEIVED'

export const START_REAL_TIME_UPDATES = 'START_REAL_TIME_UPDATES'
